// ─── Styles ───────────────────────────────────────────────
 const styles = {
  page: {
    minHeight: "100vh",
    backgroundColor: "#f5f5f5",
    padding: "32px 24px",
    fontFamily: "'Segoe UI', sans-serif",
  },
  tabs: {
    display: "flex",
    gap: "12px",
    marginBottom: "24px",
  },
  tab: {
    padding: "10px 24px",
    borderRadius: "999px",
    fontSize: "14px",
    fontWeight: "600",
    cursor: "pointer",
    border: "1.5px solid transparent",
    transition: "all 0.2s ease",
  },
  tabActive: {
    backgroundColor: "#009688",
    color: "#ffffff",
    border: "1.5px solid #009688",
  },
  tabInactive: {
    backgroundColor: "transparent",
    color: "#333",
    border: "1.5px solid #d1d5db",
  },
  card: {
    backgroundColor: "#ffffff",
    borderRadius: "16px",
    padding: "28px 32px",
    boxShadow: "0 2px 12px rgba(0,0,0,0.07)",
    maxWidth: "860px",
  },
  cardHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: "20px",
  },
  avatarRow: {
    display: "flex",
    alignItems: "center",
    gap: "16px",
  },
  avatarImg: {
    width: "60px",
    height: "60px",
    borderRadius: "50%",
    objectFit: "cover",
  },
  avatarFallback: {
    width: "60px",
    height: "60px",
    borderRadius: "50%",
    backgroundColor: "#009688",
    color: "#fff",
    fontSize: "24px",
    fontWeight: "700",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  userName: {
    fontSize: "20px",
    fontWeight: "700",
    color: "#111827",
  },
  saveBtn: {
    backgroundColor: "#009688",
    color: "#fff",
    border: "none",
    borderRadius: "8px",
    padding: "10px 28px",
    fontSize: "14px",
    fontWeight: "600",
    cursor: "pointer",
    transition: "background 0.2s",
  },
  divider: {
    height: "1px",
    backgroundColor: "#e5e7eb",
    margin: "0 0 24px 0",
  },
  grid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "20px 32px",
  },
  fieldGroup: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
  },
  label: {
    fontSize: "13px",
    fontWeight: "600",
    color: "#374151",
  },
  input: {
    border: "none",
    borderBottom: "1.5px solid #e5e7eb",
    outline: "none",
    padding: "10px 0",
    fontSize: "14px",
    color: "#111827",
    backgroundColor: "transparent",
    width: "100%",
    transition: "border-color 0.2s",
  },
  inputError: {
    borderBottomColor: "#ef4444",
  },
  errorText: {
    fontSize: "12px",
    color: "#ef4444",
  },
  passwordWrapper: {
    position: "relative",
  },
  eyeBtn: {
    position: "absolute",
    right: "0",
    top: "50%",
    transform: "translateY(-50%)",
    background: "none",
    border: "none",
    cursor: "pointer",
    color: "#9ca3af",
    padding: "4px",
    display: "flex",
    alignItems: "center",
  },
};

export default styles;